### ISSUE TITLE
Allow ".ts" in addition to "ts" when configuring extensions for Babel

### ISSUE THREAD

**Issue by vedantroy** [avajs/babel#27]
Right now, if we want to specify file extensions, we have to use `["ts", "js"]` etc. However, this differs from the way @babel/register accepts extensions, example:

```javascript
require('@babel/register')({
   extensions: ['.ts']
})
```
This creates an inconsistency, because it means we cannot use the same configuration for configuring both @babel/register and @ava/babel. Would it be possible to add support for `".ts"`, so that people can use the same configuration for multiple tools?

**Comment by novemberborn** [comment]
> because it means we cannot use the same configuration for configuring both @babel/register and @ava/babel.

But you can't, really, anyway. In that: you can't reuse the same object.

I understand the frustration with the inconsistency, but similarly I don't want to have different syntaxes _within_ AVA, and I don't think it's worth having a breaking change over this either.
