### ISSUE TITLE
Enabling Babel as described in docs causes AVA 4 to exit with error

### ISSUE THREAD

**Issue by scottdotjs** [avajs/babel#36]
The documentation tells you to enable Babel support like this:
```json
"ava": {
	"babel": true
}

```

But it's out of date, that causes AVA 4 to exit with the error "Built-in Babel support has been removed."

What do we need to do? I tried this Babel configuration, but it didn't seem to help.

```json
"env": {
	"test": {
		"plugins": [
			"rewire"
		],
		"presets": [
			"@ava/babel/stage-4"
		]
	}
}

```

My AVA config is simply:

```json
"ava": {
	"files": [
		"test/**/*"
	]
}
```

**Comment by novemberborn** [comment]
I've updated the README to reflect this only works with AVA 3.

I think using `@babel/register` is probably the way to go. I'll open an issue on AVA relating to the documentation there.

**Comment by novemberborn** [comment]
The problem has been the lack of contributions to this package, combined with improved ESM support in AVA 4 that the current version cannot make use of.

**Comment by scottdotjs** [comment]
Thanks @novemberborn. I did actually originally created this as an issue there, so I'll reopen it for your comments.
