### ISSUE TITLE
BigInt literals cause tests to not be recognized

### ISSUE THREAD

**Issue by broofa** [avajs/babel#4]
With `node@10.15.3` (i.e. BigInt support enabled) and `ava@2.2.0`:

Runs test and passes
```
test('main', t => t.is(123, 123));
```
Output: `1 test passed [06:42:47]`

```
test('main', t => t.is(123n, 123n));
```
Output: `✖ Couldn't find any files to test`

**Comment by broofa** [comment]
Closed, as in "resolved" or "wont fix" or...?

**Comment by novemberborn** [comment]
As in, looks like this should already be working. With v2 even. I think.

Note that this is now part of a new package to be used with AVA v3. Which will be out soon (unofficially, I'm too tired to write the release notes).
